#ifndef __ISIS_CMDCODES__
#define __ISIS_CMDCODES__

#define ISIS_CONFIG_NODE_ENABLE  1
#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL 2
#define CMDCODE_CONF_NODE_ISIS_PROTO_INTF_ALL_ENABLE 3
#define CMDCODE_CONF_NODE_ISIS_PROTO_INTF_ENABLE 4
#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL_ALL_INTF    5
#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL_ONE_INTF    6

#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL_LSDB 7

#endif 