#ifndef __ISIS_CMDCODES__
#define __ISIS_CMDCODES__

#define ISIS_CONFIG_NODE_ENABLE 1
#define ISIS_SHOW_NODE_ENABLE 2
#define CMDCODE_CONFIG_ISIS_PROTO_ALL_INTF_ENABLE 2
#define CMDCODE_CONFIG_ISIS_PROTO_INTF_ENABLE 3

#endif
