#ifndef __RTM_ERROR__
#define __RTM_ERROR__


typedef enum rtm_error_ {

    RTM_SUCCESS,
    RTM_ERROR_INVALID_PREFIX,
    RTM_ERROR_INVALID_NH,
    RTM_ERROR_INVALID_ROUTE,
    RTM_ERROR_INVALID_API,
    RTM_ERROR_INVALID_ARGUMENT,
    RTM_ERROR_CONTAINER_INSERTION_FAILED,
    RTM_ERROR_CONTAINER_LOOKUP_FAILED,
    RTM_ERROR_CONTAINER_REMOVAL_FAILED,
    RTM_ERROR_UPDATE_FAILED,
    RTM_ERROR_LINK_FAILED,
    RTM_ERROR_UNLINK_FAILED,
    RTM_ERROR_NEXTHOP_NOT_FOUND,
    RTM_ERROR_NEXTHOP_ALREADY_EXISTS,
    RTM_ERROR_PROTO_INFO_ALREADY_EXISTS,
    RTM_ERROR_MAX

} rtm_error_t;

#endif 