#define CMDCODE_SHOW_NW_TOPOLOGY 1
#define CMDCODE_RESOLVE_IP 2
#define CMDCODE_SHOW_NODE_ARP_TABLE 3
#define CMDCODE_SHOW_NODE_MAC_TABLE 4
#define CMDCODE_CONF_NODE_L3ROUTE 5
#define CMDCODE_PING 6
#define CMDCODE_SHOW_NODE_RT_TABLE 7
#define CMDCODE_ERO_PING 8